stages:
  - build

variables:
  PYTHONPATH: $CI_PROJECT_DIR

lint_and_test:
  stage: build
  image: python:3.8
  script:
    - pip install --upgrade pip
    - pip install pylint pytest
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - pylint --output-format=text --fail-under=9 --jobs=0 $(git ls-files '*.py')
    - pytest
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
